BUILD_SRC = .
BUILD_DIR = ./build
BUILD_DIR_TEST = $(BUILD_DIR)/test
BUILD_TYPE = debug
BUILD_EXPORT_COMPILE_COMMANDS = ON
CMAKE=cmake

build:
	$(CMAKE) -S $(BUILD_SRC) -B $(BUILD_DIR) -DCMAKE_BUILD_TYPE=$(BUILD_TYPE) -DCMAKE_EXPORT_COMPILE_COMMANDS=$(BUILD_EXPORT_COMPILE_COMMANDS)
	$(CMAKE) --build $(BUILD_DIR)

check:
	$(BUILD_DIR_TEST)/tests

clean:
	@rm -rf $(BUILD_DIR)
