name: Makefile CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
          chmod +x ./dependencies/install.sh
          ./dependencies/install.sh
    
    - name: Build
      run: make build
      
    - name: Run tests with coverage report
      run: make check-with-coverage
